// Catalogue du prototype. Pour ajouter un produit, ajoute un objet ici.
// `type` choisit la silhouette dessinée (voir SHAPES dans app.js).
const PRODUCTS = [
  {
    id: "tee-essential",
    name: "Tee Oversize Essential",
    cat: "hauts",
    type: "tee",
    price: 35,
    badge: "Best-seller",
    desc: "Coton bio 240 g/m², coupe boxy, épaules tombantes. Le tee qu'on finit par porter tous les jours.",
    colors: [
      { name: "Noir", hex: "#1a1a1a" },
      { name: "Écru", hex: "#ece6d8" },
      { name: "Kaki", hex: "#6b6a4b" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "hoodie-heavy",
    name: "Hoodie Heavyweight",
    cat: "hauts",
    type: "hoodie",
    price: 89,
    badge: "Nouveau",
    drape: "hoodie", // référence à créer dans le back-office Drope (sinon : produit-inconnu)
    desc: "Molleton gratté 450 g/m², capuche double épaisseur, poche kangourou. Lavé pour un toucher déjà rodé.",
    colors: [
      { name: "Gris chiné", hex: "#9a9a9a" },
      { name: "Bordeaux", hex: "#5e1f2a" },
      { name: "Noir", hex: "#1a1a1a" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "jacket-work",
    name: "Veste Work Canvas",
    cat: "hauts",
    type: "jacket",
    price: 149,
    badge: "Stock limité",
    desc: "Toile de coton 12 oz, zip métal, poches plaquées. Inspirée des vestes d'atelier, coupée plus large.",
    colors: [
      { name: "Camel", hex: "#a8773f" },
      { name: "Marine", hex: "#1f2a44" },
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "crew-sweat",
    name: "Sweat Col Rond",
    cat: "hauts",
    type: "sweat",
    price: 69,
    desc: "Molleton 380 g/m², bord-côtes épais aux poignets et à la taille. Simple, solide.",
    colors: [
      { name: "Vert forêt", hex: "#2f4a3a" },
      { name: "Écru", hex: "#ece6d8" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "pull-bleu",
    name: "Pull Bleu",
    cat: "hauts",
    type: "sweat",
    price: 79,
    badge: "Personnalisable",
    drape: "sweat", // produit Drape : affiche le bouton « Personnaliser »
    desc: "Maille épaisse, col rond côtelé, coupe droite. Personnalise-le en 3D avant de commander.",
    colors: [
      { name: "Bleu roi", hex: "#2b4fd6" },
      { name: "Bleu marine", hex: "#1f2a44" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "cargo",
    name: "Pantalon Cargo Ripstop",
    cat: "bas",
    type: "pants",
    price: 95,
    badge: "Nouveau",
    desc: "Ripstop déperlant, six poches, chevilles ajustables par cordon. Taille élastiquée au dos.",
    colors: [
      { name: "Olive", hex: "#4f5136" },
      { name: "Noir", hex: "#1a1a1a" },
      { name: "Sable", hex: "#c8b48e" },
    ],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "jogger",
    name: "Jogging Loose",
    cat: "bas",
    type: "pants",
    price: 65,
    desc: "Même molleton que le hoodie, jambe large et droite. À assortir ou pas.",
    colors: [
      { name: "Gris chiné", hex: "#9a9a9a" },
      { name: "Noir", hex: "#1a1a1a" },
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "shorts",
    name: "Short Nylon",
    cat: "bas",
    type: "shorts",
    price: 45,
    desc: "Nylon léger, doublure mesh, poche zippée. Pour la chaleur ou le terrain.",
    colors: [
      { name: "Bleu électrique", hex: "#2b4fd6" },
      { name: "Noir", hex: "#1a1a1a" },
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "cap",
    name: "Casquette 6 Panneaux",
    cat: "accessoires",
    type: "cap",
    price: 32,
    desc: "Twill de coton délavé, logo brodé ton sur ton, attache métal réglable.",
    colors: [
      { name: "Noir", hex: "#1a1a1a" },
      { name: "Crème", hex: "#e8dcc0" },
      { name: "Bordeaux", hex: "#5e1f2a" },
    ],
    sizes: ["Unique"],
  },
  {
    id: "beanie",
    name: "Bonnet Côtelé",
    cat: "accessoires",
    type: "beanie",
    price: 28,
    badge: "Best-seller",
    desc: "Laine mérinos mélangée, revers large. Ne gratte pas, promis.",
    colors: [
      { name: "Orange", hex: "#d4622a" },
      { name: "Gris chiné", hex: "#9a9a9a" },
      { name: "Noir", hex: "#1a1a1a" },
    ],
    sizes: ["Unique"],
  },
  {
    id: "tote",
    name: "Tote Bag Épais",
    cat: "accessoires",
    type: "tote",
    price: 25,
    desc: "Toile 16 oz, anses renforcées, poche intérieure. Tient un ordi et des courses.",
    colors: [
      { name: "Écru", hex: "#ece6d8" },
      { name: "Noir", hex: "#1a1a1a" },
    ],
    sizes: ["Unique"],
  },
];
